//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "Students")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    pub major_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::majors::Entity",
        from = "Column::MajorId",
        to = "super::majors::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Majors,
}

impl Related<super::majors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Majors.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
