//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "Students")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    pub major_id: Option<i64>,
    #[sea_orm(
        belongs_to,
        from = "major_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub majors: HasOne<super::majors::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
