use axum::{Router, routing::get};
use axum_server::tls_rustls::RustlsConfig;
use dotenvy::dotenv;
use std::net::SocketAddr;

// autogenerated database bindings from SeaORM
mod entity;

mod routes;

async fn hello_world() -> String {
    "Hello, World!".to_string()
}

#[tokio::main]
async fn main() {
    // load environment variables from .env file, needed for db connections
    dotenv().ok();

    // load certificates
    let config = RustlsConfig::from_pem_file("certs/cert.pem", "certs/key.pem")
        .await
        .expect("Failed to load certificates");

    // route paths
    let app = Router::new().route("/", get(hello_world)).route(
        "/students/get_first",
        get(routes::students::get_first_student),
    );

    // show time baby
    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    println!("Running on https://{}", addr);

    axum_server::bind_rustls(addr, config)
        .serve(app.into_make_service())
        .await
        .unwrap();
}
