mod auth;
mod entity; // autogenerated database bindings from SeaORM
mod routes;

use auth::JWTAuthDecoderState;
use axum::{
    Router,
    routing::{get, post, put},
};
use dotenvy::dotenv;
use std::net::SocketAddr;

async fn hello_world() -> String {
    "Hello, World!".to_string()
}

#[tokio::main]
async fn main() {
    // load environment variables from .env file, needed for db connections
    dotenv().ok();

    // builds a decoder used for parsing JSON Web Tokens into SupabaseClaims structs, which contain auth info like user id and token expiration time.
    let jwt_decoder = JWTAuthDecoderState::new().await;

    // route paths
    let app = Router::new()
        .route("/", get(hello_world))
        .route("/users/", post(routes::users::create))
        .route(
            "/users/favorite_number",
            get(routes::users::get_favorite_number),
        )
        .route(
            "/users/favorite_number",
            put(routes::users::set_favorite_number),
        )
        .with_state(jwt_decoder);

    // show time baby
    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    println!("Running on http://{}", addr);

    axum_server::bind(addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}
