//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "default_tags_removed")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_id: i64,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub song_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::default_tags_applied::Entity",
        from = "(Column::TagId, Column::SongId)",
        to = "(super::default_tags_applied::Column::TagId, super::default_tags_applied::Column::SongId)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    DefaultTagsApplied,
}

impl Related<super::default_tags_applied::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DefaultTagsApplied.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        super::default_tags_applied::Relation::Tags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::default_tags_applied::Relation::DefaultTagsRemoved
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
