//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "default_tags_applied")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub song_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_id: i64,
    #[sea_orm(
        belongs_to,
        from = "tag_id",
        to = "tag_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub tags: BelongsTo<super::tags::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
