//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "global_tags_applied")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub song_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::global_tags::Entity",
        from = "Column::TagId",
        to = "super::global_tags::Column::TagId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    GlobalTags,
}

impl Related<super::global_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlobalTags.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
