//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::Interest;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "interests")]
pub struct Model {
    #[sea_orm(column_type = "Text", unique_key = "interests_name_interest_type_key")]
    pub name: String,
    #[sea_orm(
        ignore,
        column_type = "custom(\"vector\")",
        select_as = "text",
        nullable
    )]
    pub embedding: Option<String>,
    #[sea_orm(primary_key)]
    pub interest_id: i64,
    #[sea_orm(unique_key = "interests_name_interest_type_key")]
    pub interest_type: Interest,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::interest_scores::Entity")]
    InterestScores,
}

impl Related<super::interest_scores::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InterestScores.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
