//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "interest_scores")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub interest_id: i64,
    pub score: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::interests::Entity",
        from = "Column::InterestId",
        to = "super::interests::Column::InterestId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Interests,
}

impl Related<super::interests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Interests.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
