//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "listening_events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub event_id: i64,
    #[sea_orm(unique_key = "listening_events_idempotency_idx")]
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub event_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub song_id: Option<String>,
    pub occurred_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub client_tz: String,
    pub session_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", unique_key = "listening_events_idempotency_idx")]
    pub client_event_id: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub payload: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
