//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "metadata_song_tags_applied")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub song_id: String,
    pub found: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub artist_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub album_id: Option<String>,
    pub duration_in_millis: Option<i32>,
    pub genre_names: Vec<String>,
    pub release_date: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    pub content_rating: Option<String>,
    pub fetched_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub album_name: Option<String>,
    pub total_plays: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
