//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "posts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub post_id: i64,
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(
        ignore,
        column_type = "custom(\"vector\")",
        select_as = "text",
        nullable
    )]
    pub embedding: Option<String>,
    pub views: i64,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
