//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::default_tags_applied::Entity as DefaultTagsApplied;
pub use super::tags::Entity as Tags;
pub use super::user_tags_applied::Entity as UserTagsApplied;
