//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "tag_type")]
pub enum TagType {
    #[sea_orm(string_value = "basic")]
    Basic,
    #[sea_orm(string_value = "text")]
    Text,
    #[sea_orm(string_value = "datetime")]
    Datetime,
    #[sea_orm(string_value = "number")]
    Number,
    #[sea_orm(string_value = "checkbox")]
    Checkbox,
}
