//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "songs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub song_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::applied_tags::Entity")]
    AppliedTags,
}

impl Related<super::applied_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppliedTags.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
