//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::TagType;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub tag_id: i64,
    pub user_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub color: String,
    pub r#type: TagType,
    #[sea_orm(has_many)]
    pub default_tags_applieds: HasMany<super::default_tags_applied::Entity>,
    #[sea_orm(has_many)]
    pub user_tags_applieds: HasMany<super::user_tags_applied::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
