//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::TagType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub tag_id: i64,
    pub user_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub color: String,
    pub r#type: TagType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::default_tags_applied::Entity")]
    DefaultTagsApplied,
    #[sea_orm(has_many = "super::user_tags_applied::Entity")]
    UserTagsApplied,
}

impl Related<super::default_tags_applied::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DefaultTagsApplied.def()
    }
}

impl Related<super::user_tags_applied::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserTagsApplied.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
